### PR TITLE
Added some conventions

### LINKED ISSUE #12: Branch naming convention
Just to standardise some git conventions, I am proposing the following naming convention - 

`<type-of-branch>/<feature-name>` 

For example, I have started off by pushing `feat/fetch-mp3-url` 

What do you guys think? 

@whoiswillma @bartekpacia @emctackett

### PR DESCRIPTION
**Pull request by bartekpacia**
Added `CONTRIBUTING.md`, where we'll be adding conventions (as we will invent them in the upcoming days).

fixes #12

### CODE REVIEW

**Comment by bartekpacia** [comment]
@emctackett @whoiswillma @lionellloh It's the simplest PR one could make, but I'm pinging you so we can maybe set up some rules for code review etc?

**Comment by emctackett** [comment]
@bartekpacia My opinion: yes, I think when a contributor's PR is ready to be reviewed, they should assign two reviewers via the right sidebar.  After approval from both reviewers, then someone can merge!  :+1:

**Comment by emctackett** [comment]
Other conventions to follow (IMO):
- If your PR addresses an issue, reference the issue in the title of the PR
- If you are going to work on an issue (and eventually submit a PR), formally assign the issue to yourself so that the team can see you've claimed it.

**Comment by bartekpacia** [comment]
@emctackett added your suggestions

**Pull request merged**
